### ISSUE TITLE
Room Number Formatting

### ISSUE THREAD

**Issue by cpacheco4983** [soft-eng-practicum/ggcmaps#10]
### Description: 
When searching a room number in Internet Explorer, after the building map is loaded the number formatting in the search bar is not formatted.

### Reproduce by:
1. Open Internet Explorer
2. Go to map
3. Search a specific room number (ie: b1950)
4. Room number will not be formatted correctly in search bar (ie: B 1950)

**Comment by Dave89rr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [In IE: Room number format after search not correct](https://trello.com/c/y59m1ayJ/52-in-ie-when-searching-a-room-b1950-the-correct-map-will-load-but-the-room-is-not-highlighted-and-the-number-in-the-search-bar-is-)
