### ISSUE TITLE
Missing Rooms

### ISSUE THREAD

**Issue by Dave89rr** [soft-eng-practicum/ggcmaps#11]
### Description:
Whenever certain rooms are searched an alert comes up stating it cannot be found before loading the respective building on the map.
Missing Rooms:
* ~B 1200~
* D 1301

### Recreate by:
* Enter one of the rooms listed above in the search bar
  * Formatting options in search:
    * ~B1200~ or D1301 (without space)
    * ~B 1200~ or D 1301 (with space)

### Time Log:
| User | Date  | Start Time | End Time | Total |
| ----- | ------ | ----------- | ---------- |------ |
| Dave89rr | 2/25/2017 | 19:28 | 19:29 | 0:01 |
| cpacheco4983 | 2/27/2017 | 12:15 | 12:30 | 0:15 |
| Dave89rr | 3/1/2017 | 13:34 | 13:37 | 0:03 |
|mmuse90| 3/1/2017 | 15:03 | 15:23 | 0:20 |

## Hours-to-date: 0:19
* **Dave89rr: 0:04**
* **JGerth92: ---**
* **cpacheco4983: 0:15**
* **mmuse90: 0:20**

**Comment by Dave89rr** [comment]
@JGerth92 fixed the missing B 1200 room in search. 
The missing room D 1301 is a mistake in the `SVG` file for the building.

**Comment by Dave89rr** [comment]
C 2100 has a typo in the `svg` and shows up as C210 in the map, makes it unsearchable.

**Comment by mmuse90** [comment]
D 1301 has no <g onclick= "activate room..." svg tag in the file for D building, first floor, or at least that I could find.... explains why it's not searchable.

**Comment by Dave89rr** [comment]
Moved all information pertaining to room D 1301 to issue #21
