### ISSUE TITLE
Chick-Fil-A is not searchable by name

### ISSUE THREAD

**Issue by JGerth92** [soft-eng-practicum/ggcmaps#18]
### Description:
When searching for "Chick-Fil-A" by name in the search bar an invalid room error is received. After dismissing message the search bar shortens the name to "chick-fil", I believe this to be the problem; chick-fil-a is present in the roomNames.json, so I don't believe the problem lies there.

### Time Log:
| User | Date  | Start Time | End Time | Total |
| ----- | ------ | ----------- | ---------- |------ |
| Dave89rr | 2/25/2017 | 8:05 | 8:32 | 0:27 |
| Dave89rr | 2/27/2017 | 14:49 | 15:05 | 0:16 |
| JGerth92 | 2/25/2017 | 7:40 | 8:00 | 0:20 |
| cpacheco4983 | 2/28/2017 | 21:15 | 21:51 | 0:36 |

## Hours-to-date: 1:39
* **Dave89rr: 0:43**
* **JGerth92: 0:20**
* **cpacheco4983: 0:36**

**Comment by Dave89rr** [comment]
Temporary solution: Added "Chick Fil" and "Chick" as searchable options

**Comment by cpacheco4983** [comment]
Looked at: 
rooms.js ln465 `function searchRoomNumber()`
utils.js ln14 `function parseSearch(str)`
Had trouble looking at script.min.js
Atom would slow to a crawl
