### ISSUE TITLE
Double Alert Room Numbers

### ISSUE THREAD

**Issue by Dave89rr** [soft-eng-practicum/ggcmaps#19]
### Description:
When the user types in an invalid room name/number, the website throws the same alert twice.

### Recreate by:
* In the search bar type random letters or random numbers

### Time Log:
| User | Date  | Start Time | End Time | Total |
| ----- | ------ | ----------- | ---------- |------ |
| Dave89rr | 2/27/2017 | 9:58 | 10:13 | 0:15 |
| Dave89rr | 2/27/2017 | 14:10 | 14:49 | 0:39 |
| cpacheco4983 | 2/28/2017 | 11:39 | 11:49 | 0:10 |
| cpacheco4983 | 3/25/2017 | 11:10 | 11:40 | 0:30 |
| cpacheco4983 | 2/27/2017 | 07:45 | 09:03 | 1:18 |

## Hours-to-Date: 1:04
* **Dave89rr: 0:54**
* **cpacheco4983: 1:58**

**Comment by cpacheco4983** [comment]
Only shows a second alert per query. 

1.Type invalid room -> Alert shows 2x 
2.Search for same invalid room -> Alert only displays 1x
3.Type different invalid room -> Alert shows 2x

**Comment by cpacheco4983** [comment]
`  urlRoom();

  // If the user goes back in the browser reload the last loction
  window.addEventListener('popstate', function(e) {
    urlRoom();`

commenting out urlRoom in function gets rid of second alert but also back button functionality.

**Comment by JGerth92** [comment]
The path taken if searchFromMenu() is uncommented in urlRoom()

* searchFromBar()
* searchRoomNumber()
* parseSearch()
    * Does its thing
    * Returns to searchRoomNumbers()
* Back in searchRoomNumbers()
    * else statement
        * Not 4983
        * switch statement
        * upperHash()
    * urlRoom()
        * switch statement —> default statement
        * searchFromMenu()
            * closeMenu()
            * parseSearch()
                * Does its thing
            * searchRoomNumber()
                * parseSearch()
                    * Does its thing
                * else statement
                    * Not 4983
                    * switch statement
                    * upperHash() —> does not go to urlRoom()
                    * activateRoom()
                        * ALERT!!!
    * switch statement
    * activateRoom()
        * ALERT!!!
* Fin.
