### ISSUE TITLE
Single letter search glitch

### ISSUE THREAD

**Issue by mmuse90** [soft-eng-practicum/ggcmaps#23]
### Description:
Typing some letters by themselves into the search bar results in an error loop

Recreate:
Type "A" into search bar 
Type "D" into search bar 
Type "P" into search bar 
Type "X" into search bar 
Type "Y" into search bar 
Type "Z" into search bar 

Relevant info:
error loop is duplicating and removing any capitalization of the original search. ex, P becomes 'pp'

Despite error, some buildings are found, which is intended, and some are not.
Found:
A
B
C3 - error message is only displayed once
Not Found:
C
D
F
H
I
L
### Time Log:
| User | Date  | Start Time | End Time | Total |
| JGerth92 | 03/03/2017 | 13:33 | 13:47 | 0:14 |
| cpacheco4983 | 03/04/2017 | 00:09 | 00:16 | 0:07 |
| cpacheco4983 | 03/04/2017 | 15:05 | 15:47 | 0:42 |
| cpacheco4983 | 03/07/2017 | 12:40 | 13:11 | 0:31 |
| cpacheco4983 | 03/07/2017 | 17:04 | 18:29 | 1:25 |

## Hours-to-date: 
* **JGerth92: 0:14**
* **cpacheco4983: 2:45**

**Comment by cpacheco4983** [comment]
The error messages that pop up are in rooms.js lines 405, 514 and 640. I think these would be good points to look through for a solution.

**Comment by cpacheco4983** [comment]
Should be fixed now. Letters not pertaining to building should redirect to campus map.
