### ISSUE TITLE
Highlight room alert

### ISSUE THREAD

**Issue by cpacheco4983** [soft-eng-practicum/ggcmaps#61]
Pull up building map and click named rooms. Only works for some. Error "Sorry, room number ******* couldn't be found in this building." pops up.

Only rooms with names that contain more than one word?

Building:
A
Chick-Fil-A, Panda-Express
B
F1: Enstein-Bros-Bagels
E 
F1: Private-Dining, Game-Room, Multi-Purpose-Room, Dining-Hall, Outdoor-Dining, Food-Stations, Kitchen-Area
F2: Info-Desk, Catering-Kitchen
F
F1: Mens-Lockers, Womens-Lockers, Racquet-Ball-Court-1, Racquet-Ball-Court-2, Racquet-Ball-Court-3, Jr-Olympic-Pool, Basketball-Court
F2: Weight-Machines, Free-Weights, Spin-Room, Elevated-Track

**Comment by Dave89rr** [comment]
You failed to pull. This has been fixed
