### ISSUE TITLE
Floor Change Drop-Down

### ISSUE THREAD

**Issue by Dave89rr** [soft-eng-practicum/ggcmaps#9]
### Description:
The floor drop-down (in the search bar) doesn't work after showing search results. **Edit:** The drop-down shows Floor 1 regardless of what floor was selected.

### Recreate by:
* Search a room in building with multiple floors (ex: B 1100)
* Click on ~another~ ***any*** floor in the search bar drop-down menu
[Map ~flickers~ ***jumps to first floor*** and removes highlight]
* Click on drop-down again and it changes the floor shown

### Time Log:
| User | Date  | Start Time | End Time | Total |
| ----- | ------ | ----------- | ---------- |------ |
| Dave89rr | 2/27/2017 | 12:20 | 12:32 | 0:12 |
| Dave89rr | 2/27/2017 | 13:00 | 13:35 | 0:35 |
| Dave89rr | 2/28/2017 | 17:43 | 18:07 | 0:24 |
| Dave89rr | 3/1/2017 | 13:20 | **null** | ~0:21 |

## Hours-to-Date: 1:11
* **Dave89rr: 1:11**

**Comment by Dave89rr** [comment]
### Discovery:
Highlight of the room has nothing to do with the flicker/glitch. Adding a `removeHighlight()` to the drop-down merely removes the highlight before a new floor is selected. Regardless of floor chosen the map flickers to the selected floor and changes to base floor.

**Comment by cpacheco4983** [comment]
Floors will switch without problem if only the building was searched for. 

Reproduction:
Search for B building
Click floor dropdown and switch floor 
Correct floor will pull up.

Search for B1200 
Click floor drop down and switch floor
Map will switch then switch back
Click floor drop down and switch floor
Correct floor will pull up

**Comment by Dave89rr** [comment]
@cengique don't worry, you don't have to work on this anymore 😂 😂
